import { mount, flushPromises, enableAutoUnmount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, it, expect, vi } from 'vitest'
import IQCheckResultsModal from '../IQCheckResultsModal.vue'
import type { Account } from '@/types'
import { downloadIQCheckDiagnostics } from '@/api/admin/accounts'
vi.mock('@/api/admin/accounts', () => ({ downloadIQCheckDiagnostics: vi.fn() }))
const { history, status, run } = vi.hoisted(() => ({ history: vi.fn(), status: vi.fn(), run: vi.fn() }))
vi.mock('@/api/admin', () => ({ adminAPI: { accounts: { getIQCheckResults: history, getIQCheckStatus: status, runIQCheck: run } } }))
vi.mock('@/utils/format', () => ({ formatDateTime: (s: string) => s }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (s: string) => s, te: () => true }) }))
describe('IQ results', () => {
  enableAutoUnmount(afterEach)
  beforeEach(() => {
    vi.clearAllMocks()
    status.mockResolvedValue({ enabled: true, status: 'smart', execution_state: 'deferred', execution_reason: 'account_busy', freshness: 'stale', last_run_at: '2026-09-15T04:39:27Z', next_eligible_at: '2026-09-15T05:04:17Z', budget_remaining: 4 })
  })
  afterEach(() => { vi.useRealTimers() })
  it('loads current execution information even when no attempt was started', async () => {
    history.mockResolvedValue([])
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    const summary = wrapper.get('[data-testid="iq-current-state"]')
    expect(summary.text()).toContain('iqExecutionStates.deferred')
    expect(summary.text()).toContain('iqExecutionReasons.account_busy')
    expect(summary.text()).toContain('iqFreshness.stale')
    expect(summary.text()).toContain('2026-09-15T05:04:17Z')
    expect(wrapper.text()).toContain('iqEmpty')
    expect(wrapper.emitted('updated')).toHaveLength(1)
  })
  it('preserves loaded records on a refresh failure and stops requests on close', async () => {
    vi.useFakeTimers()
    history.mockResolvedValue([{ id: 1, status: 'smart', started_at: 'now', finished_at: 'now', latency_ms: 1 }])
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    history.mockRejectedValueOnce(new Error('offline'))
    status.mockRejectedValueOnce(new Error('offline'))
    await wrapper.get('button[aria-label="common.refresh"]').trigger('click')
    await flushPromises()
    expect(wrapper.findAll('li')).toHaveLength(1)
    expect(wrapper.text()).toContain('iqHistoryFailed')
    expect(wrapper.text()).toContain('iqStatusFailed')
    await wrapper.setProps({ show: false })
    await vi.advanceTimersByTimeAsync(30000)
    expect(history).toHaveBeenCalledTimes(2)
    expect(history.mock.calls[1][1].aborted).toBe(true)
  })
  it('does not apply an old account status after switching accounts', async () => {
    let resolve!: (data: unknown) => void
    status.mockImplementationOnce(() => new Promise(r => { resolve = r }))
    history.mockResolvedValue([])
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await wrapper.setProps({ account: { id: 9 } as Account })
    await flushPromises()
    resolve({ enabled: true, execution_reason: 'old-account-secret' })
    await flushPromises()
    expect(wrapper.text()).not.toContain('old-account-secret')
    expect(wrapper.emitted('updated')).toHaveLength(1)
  })
  it('queues once and refreshes the current state', async () => {
    history.mockResolvedValue([])
    let resolve!: (data: unknown) => void
    run.mockImplementationOnce(() => new Promise(r => { resolve = r }))
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    const button = wrapper.findAll('button').find(button => button.text().includes('iqRun'))!
    await button.trigger('click')
    await button.trigger('click')
    expect(run).toHaveBeenCalledTimes(1)
    resolve({ queued: true, next_eligible_at: 'later' })
    await flushPromises()
    expect(wrapper.text()).toContain('iqQueuedAt')
    expect(status).toHaveBeenCalledTimes(2)
  })
  it('shows three records and keeps them visible when a diagnostic download fails', async () => {
    history.mockResolvedValue([3, 2, 1].map(id => ({ id, status: 'smart', normalized_answer: '21', started_at: 'now', finished_at: 'now', latency_ms: 1250, model: 'custom', effort: 'low' })))
    vi.mocked(downloadIQCheckDiagnostics).mockRejectedValueOnce(new Error('offline'))
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    expect(wrapper.findAll('li')).toHaveLength(3)
    await wrapper.findAll('button').find(button => button.text().includes('iqDownload'))!.trigger('click')
    await flushPromises()
    expect(wrapper.findAll('li')).toHaveLength(3)
    expect(wrapper.get('[role="alert"]').text()).toContain('iqDownloadFailed')
    expect(wrapper.text()).toContain('1.25 s')
  })
  it('discards a late response after changing accounts', async () => {
    let resolve!: (rows: unknown[]) => void
    history.mockImplementationOnce(() => new Promise(r => { resolve = r }))
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    history.mockResolvedValueOnce([])
    await wrapper.setProps({ account: { id: 9 } as Account })
    await flushPromises()
    resolve([{ id: 1, model: 'old-account' }]); await flushPromises()
    expect(wrapper.text()).not.toContain('old-account')
    expect(wrapper.text()).toContain('iqEmpty')
  })
  it('shows the same extracted answer for JSON and prose while preserving folded originals', async () => {
    history.mockResolvedValue([
      { id: 2, normalized_answer: '21', answer: '{"answer":21}', model: 'custom', effort: 'ultra', protocol: 'responses', output_mode: 'strict', status: 'smart', finished_at: 'now', started_at: 'now', latency_ms: 12, grader_version: 'candy-grader-v2', format_compliant: true },
      { id: 1, normalized_answer: '21', answer: '最终答案是21。解释如下。', model: 'custom', effort: 'upstream_default', status: 'smart', finished_at: 'before', started_at: 'before', latency_ms: 11, grader_version: 'candy-grader-v2', format_compliant: false }
    ])
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8, name: 'fixture' } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    expect(wrapper.findAll('[data-testid="iq-answer"]').map(p => p.text())).toEqual(['21', '21'])
    expect(wrapper.findAll('details')).toHaveLength(4)
    expect(wrapper.findAll('details').every(d => d.attributes('open') === undefined)).toBe(true)
    expect(wrapper.text()).toContain('iqFormatMismatch')
    expect(wrapper.findAll('pre').map(p => p.text())).toEqual(['{"answer":21}', '最终答案是21。解释如下。'])
  })
  it('distinguishes unfinished and legacy attempts', async () => {
    history.mockResolvedValue([{ id: 1, model: 'legacy', effort: 'low', answer: '29', status: 'unknown', finished_at: null, started_at: 'now', latency_ms: 0 }])
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    expect(wrapper.text()).toContain('iqRunning')
    expect(wrapper.text()).toContain('iqLegacyResult')
    expect(wrapper.get('pre').text()).toBe('29')
  })
  it('shows bounded diagnostics separately from an absent answer', async () => {
    history.mockResolvedValue([{ id: 1, status: 'unknown', finished_at: 'now', started_at: 'now', answer: '', reason: 'invalid_event_json', diagnostic: { parser_version: 'iq-response-v3', stage: 'decode', code: 'invalid_event_json', event_type: 'response.completed', event_index: 4, http_status: 200, request_id: '<script>alert(1)</script>', unexpected_secret: 'must-not-render' } }])
    const wrapper = mount(IQCheckResultsModal, { props: { show: true, account: { id: 8 } as Account }, global: { stubs: { BaseDialog: { template: '<div><slot /></div>' } } } })
    await flushPromises()
    expect(wrapper.text()).toContain('iqReasons.invalid_event_json')
    expect(wrapper.text()).toContain('response.completed')
    expect(wrapper.text()).toContain('iq-response-v3')
    expect(wrapper.text()).not.toContain('must-not-render')
    expect(wrapper.find('script').exists()).toBe(false)
    expect(wrapper.findAll('details').every(d => d.attributes('open') === undefined)).toBe(true)
  })

})
